name: Prek action

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

permissions: {}

jobs:
  prek:
    runs-on: ubuntu-latest
    name: "prek"
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: j178/prek-action@53276d8b0d10f8b6672aa85b4588c6921d0370cc # v2
